/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// ZoneForecastGeoJsonAllOf struct for ZoneForecastGeoJsonAllOf
type ZoneForecastGeoJsonAllOf struct {
	Properties *ZoneForecast `json:"properties,omitempty"`
}

// NewZoneForecastGeoJsonAllOf instantiates a new ZoneForecastGeoJsonAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZoneForecastGeoJsonAllOf() *ZoneForecastGeoJsonAllOf {
	this := ZoneForecastGeoJsonAllOf{}
	return &this
}

// NewZoneForecastGeoJsonAllOfWithDefaults instantiates a new ZoneForecastGeoJsonAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZoneForecastGeoJsonAllOfWithDefaults() *ZoneForecastGeoJsonAllOf {
	this := ZoneForecastGeoJsonAllOf{}
	return &this
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *ZoneForecastGeoJsonAllOf) GetProperties() ZoneForecast {
	if o == nil || o.Properties == nil {
		var ret ZoneForecast
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZoneForecastGeoJsonAllOf) GetPropertiesOk() (*ZoneForecast, bool) {
	if o == nil || o.Properties == nil {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ZoneForecastGeoJsonAllOf) HasProperties() bool {
	if o != nil && o.Properties != nil {
		return true
	}

	return false
}

// SetProperties gets a reference to the given ZoneForecast and assigns it to the Properties field.
func (o *ZoneForecastGeoJsonAllOf) SetProperties(v ZoneForecast) {
	o.Properties = &v
}

func (o ZoneForecastGeoJsonAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	return json.Marshal(toSerialize)
}

type NullableZoneForecastGeoJsonAllOf struct {
	value *ZoneForecastGeoJsonAllOf
	isSet bool
}

func (v NullableZoneForecastGeoJsonAllOf) Get() *ZoneForecastGeoJsonAllOf {
	return v.value
}

func (v *NullableZoneForecastGeoJsonAllOf) Set(val *ZoneForecastGeoJsonAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableZoneForecastGeoJsonAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableZoneForecastGeoJsonAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZoneForecastGeoJsonAllOf(val *ZoneForecastGeoJsonAllOf) *NullableZoneForecastGeoJsonAllOf {
	return &NullableZoneForecastGeoJsonAllOf{value: val, isSet: true}
}

func (v NullableZoneForecastGeoJsonAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZoneForecastGeoJsonAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


