/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// ObservationCollectionGeoJson struct for ObservationCollectionGeoJson
type ObservationCollectionGeoJson struct {
	Context *JsonLdContext `json:"@context,omitempty"`
	Type string `json:"type"`
	Features []ObservationGeoJsonAllOf `json:"features"`
}

// NewObservationCollectionGeoJson instantiates a new ObservationCollectionGeoJson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObservationCollectionGeoJson(type_ string, features []ObservationGeoJsonAllOf) *ObservationCollectionGeoJson {
	this := ObservationCollectionGeoJson{}
	this.Type = type_
	this.Features = features
	return &this
}

// NewObservationCollectionGeoJsonWithDefaults instantiates a new ObservationCollectionGeoJson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObservationCollectionGeoJsonWithDefaults() *ObservationCollectionGeoJson {
	this := ObservationCollectionGeoJson{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *ObservationCollectionGeoJson) GetContext() JsonLdContext {
	if o == nil || o.Context == nil {
		var ret JsonLdContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservationCollectionGeoJson) GetContextOk() (*JsonLdContext, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *ObservationCollectionGeoJson) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given JsonLdContext and assigns it to the Context field.
func (o *ObservationCollectionGeoJson) SetContext(v JsonLdContext) {
	o.Context = &v
}

// GetType returns the Type field value
func (o *ObservationCollectionGeoJson) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ObservationCollectionGeoJson) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ObservationCollectionGeoJson) SetType(v string) {
	o.Type = v
}

// GetFeatures returns the Features field value
func (o *ObservationCollectionGeoJson) GetFeatures() []ObservationGeoJsonAllOf {
	if o == nil {
		var ret []ObservationGeoJsonAllOf
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *ObservationCollectionGeoJson) GetFeaturesOk() ([]ObservationGeoJsonAllOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.Features, true
}

// SetFeatures sets field value
func (o *ObservationCollectionGeoJson) SetFeatures(v []ObservationGeoJsonAllOf) {
	o.Features = v
}

func (o ObservationCollectionGeoJson) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Context != nil {
		toSerialize["@context"] = o.Context
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["features"] = o.Features
	}
	return json.Marshal(toSerialize)
}

type NullableObservationCollectionGeoJson struct {
	value *ObservationCollectionGeoJson
	isSet bool
}

func (v NullableObservationCollectionGeoJson) Get() *ObservationCollectionGeoJson {
	return v.value
}

func (v *NullableObservationCollectionGeoJson) Set(val *ObservationCollectionGeoJson) {
	v.value = val
	v.isSet = true
}

func (v NullableObservationCollectionGeoJson) IsSet() bool {
	return v.isSet
}

func (v *NullableObservationCollectionGeoJson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObservationCollectionGeoJson(val *ObservationCollectionGeoJson) *NullableObservationCollectionGeoJson {
	return &NullableObservationCollectionGeoJson{value: val, isSet: true}
}

func (v NullableObservationCollectionGeoJson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObservationCollectionGeoJson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


