/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// GeoJSONMultiLineString struct for GeoJSONMultiLineString
type GeoJSONMultiLineString struct {
	Type string `json:"type"`
	Coordinates [][][]float32 `json:"coordinates"`
	// A GeoJSON bounding box. Please refer to IETF RFC 7946 for information on the GeoJSON format.
	Bbox []float32 `json:"bbox,omitempty"`
}

// NewGeoJSONMultiLineString instantiates a new GeoJSONMultiLineString object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoJSONMultiLineString(type_ string, coordinates [][][]float32) *GeoJSONMultiLineString {
	this := GeoJSONMultiLineString{}
	this.Type = type_
	this.Coordinates = coordinates
	return &this
}

// NewGeoJSONMultiLineStringWithDefaults instantiates a new GeoJSONMultiLineString object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoJSONMultiLineStringWithDefaults() *GeoJSONMultiLineString {
	this := GeoJSONMultiLineString{}
	return &this
}

// GetType returns the Type field value
func (o *GeoJSONMultiLineString) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GeoJSONMultiLineString) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GeoJSONMultiLineString) SetType(v string) {
	o.Type = v
}

// GetCoordinates returns the Coordinates field value
func (o *GeoJSONMultiLineString) GetCoordinates() [][][]float32 {
	if o == nil {
		var ret [][][]float32
		return ret
	}

	return o.Coordinates
}

// GetCoordinatesOk returns a tuple with the Coordinates field value
// and a boolean to check if the value has been set.
func (o *GeoJSONMultiLineString) GetCoordinatesOk() ([][][]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Coordinates, true
}

// SetCoordinates sets field value
func (o *GeoJSONMultiLineString) SetCoordinates(v [][][]float32) {
	o.Coordinates = v
}

// GetBbox returns the Bbox field value if set, zero value otherwise.
func (o *GeoJSONMultiLineString) GetBbox() []float32 {
	if o == nil || o.Bbox == nil {
		var ret []float32
		return ret
	}
	return o.Bbox
}

// GetBboxOk returns a tuple with the Bbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJSONMultiLineString) GetBboxOk() ([]float32, bool) {
	if o == nil || o.Bbox == nil {
		return nil, false
	}
	return o.Bbox, true
}

// HasBbox returns a boolean if a field has been set.
func (o *GeoJSONMultiLineString) HasBbox() bool {
	if o != nil && o.Bbox != nil {
		return true
	}

	return false
}

// SetBbox gets a reference to the given []float32 and assigns it to the Bbox field.
func (o *GeoJSONMultiLineString) SetBbox(v []float32) {
	o.Bbox = v
}

func (o GeoJSONMultiLineString) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["coordinates"] = o.Coordinates
	}
	if o.Bbox != nil {
		toSerialize["bbox"] = o.Bbox
	}
	return json.Marshal(toSerialize)
}

type NullableGeoJSONMultiLineString struct {
	value *GeoJSONMultiLineString
	isSet bool
}

func (v NullableGeoJSONMultiLineString) Get() *GeoJSONMultiLineString {
	return v.value
}

func (v *NullableGeoJSONMultiLineString) Set(val *GeoJSONMultiLineString) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoJSONMultiLineString) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoJSONMultiLineString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoJSONMultiLineString(val *GeoJSONMultiLineString) *NullableGeoJSONMultiLineString {
	return &NullableGeoJSONMultiLineString{value: val, isSet: true}
}

func (v NullableGeoJSONMultiLineString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoJSONMultiLineString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


