/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// GridpointHazards struct for GridpointHazards
type GridpointHazards struct {
	Values []GridpointHazardsValuesInner `json:"values"`
}

// NewGridpointHazards instantiates a new GridpointHazards object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGridpointHazards(values []GridpointHazardsValuesInner) *GridpointHazards {
	this := GridpointHazards{}
	this.Values = values
	return &this
}

// NewGridpointHazardsWithDefaults instantiates a new GridpointHazards object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGridpointHazardsWithDefaults() *GridpointHazards {
	this := GridpointHazards{}
	return &this
}

// GetValues returns the Values field value
func (o *GridpointHazards) GetValues() []GridpointHazardsValuesInner {
	if o == nil {
		var ret []GridpointHazardsValuesInner
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *GridpointHazards) GetValuesOk() ([]GridpointHazardsValuesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *GridpointHazards) SetValues(v []GridpointHazardsValuesInner) {
	o.Values = v
}

func (o GridpointHazards) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["values"] = o.Values
	}
	return json.Marshal(toSerialize)
}

type NullableGridpointHazards struct {
	value *GridpointHazards
	isSet bool
}

func (v NullableGridpointHazards) Get() *GridpointHazards {
	return v.value
}

func (v *NullableGridpointHazards) Set(val *GridpointHazards) {
	v.value = val
	v.isSet = true
}

func (v NullableGridpointHazards) IsSet() bool {
	return v.isSet
}

func (v *NullableGridpointHazards) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGridpointHazards(val *GridpointHazards) *NullableGridpointHazards {
	return &NullableGridpointHazards{value: val, isSet: true}
}

func (v NullableGridpointHazards) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGridpointHazards) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


