/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// GridpointQuantitativeValueLayer A gridpoint layer consisting of quantitative values (numeric values with associated units of measure). 
type GridpointQuantitativeValueLayer struct {
	// A string denoting a unit of measure, expressed in the format \"{unit}\" or \"{namespace}:{unit}\". Units with the namespace \"wmo\" or \"wmoUnit\" are defined in the World Meteorological Organization Codes Registry at http://codes.wmo.int/common/unit and should be canonically resolvable to http://codes.wmo.int/common/unit/{unit}. Units with the namespace \"nwsUnit\" are currently custom and do not align to any standard. Units with no namespace or the namespace \"uc\" are compliant with the Unified Code for Units of Measure syntax defined at https://unitsofmeasure.org/. This also aligns with recent versions of the Geographic Markup Language (GML) standard, the IWXXM standard, and OGC Observations and Measurements v2.0 (ISO/DIS 19156). Namespaced units are considered deprecated. We will be aligning API to use the same standards as GML/IWXXM in the future. 
	Uom *string `json:"uom,omitempty"`
	Values []GridpointQuantitativeValueLayerValuesInner `json:"values"`
}

// NewGridpointQuantitativeValueLayer instantiates a new GridpointQuantitativeValueLayer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGridpointQuantitativeValueLayer(values []GridpointQuantitativeValueLayerValuesInner) *GridpointQuantitativeValueLayer {
	this := GridpointQuantitativeValueLayer{}
	this.Values = values
	return &this
}

// NewGridpointQuantitativeValueLayerWithDefaults instantiates a new GridpointQuantitativeValueLayer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGridpointQuantitativeValueLayerWithDefaults() *GridpointQuantitativeValueLayer {
	this := GridpointQuantitativeValueLayer{}
	return &this
}

// GetUom returns the Uom field value if set, zero value otherwise.
func (o *GridpointQuantitativeValueLayer) GetUom() string {
	if o == nil || o.Uom == nil {
		var ret string
		return ret
	}
	return *o.Uom
}

// GetUomOk returns a tuple with the Uom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GridpointQuantitativeValueLayer) GetUomOk() (*string, bool) {
	if o == nil || o.Uom == nil {
		return nil, false
	}
	return o.Uom, true
}

// HasUom returns a boolean if a field has been set.
func (o *GridpointQuantitativeValueLayer) HasUom() bool {
	if o != nil && o.Uom != nil {
		return true
	}

	return false
}

// SetUom gets a reference to the given string and assigns it to the Uom field.
func (o *GridpointQuantitativeValueLayer) SetUom(v string) {
	o.Uom = &v
}

// GetValues returns the Values field value
func (o *GridpointQuantitativeValueLayer) GetValues() []GridpointQuantitativeValueLayerValuesInner {
	if o == nil {
		var ret []GridpointQuantitativeValueLayerValuesInner
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *GridpointQuantitativeValueLayer) GetValuesOk() ([]GridpointQuantitativeValueLayerValuesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *GridpointQuantitativeValueLayer) SetValues(v []GridpointQuantitativeValueLayerValuesInner) {
	o.Values = v
}

func (o GridpointQuantitativeValueLayer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Uom != nil {
		toSerialize["uom"] = o.Uom
	}
	if true {
		toSerialize["values"] = o.Values
	}
	return json.Marshal(toSerialize)
}

type NullableGridpointQuantitativeValueLayer struct {
	value *GridpointQuantitativeValueLayer
	isSet bool
}

func (v NullableGridpointQuantitativeValueLayer) Get() *GridpointQuantitativeValueLayer {
	return v.value
}

func (v *NullableGridpointQuantitativeValueLayer) Set(val *GridpointQuantitativeValueLayer) {
	v.value = val
	v.isSet = true
}

func (v NullableGridpointQuantitativeValueLayer) IsSet() bool {
	return v.isSet
}

func (v *NullableGridpointQuantitativeValueLayer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGridpointQuantitativeValueLayer(val *GridpointQuantitativeValueLayer) *NullableGridpointQuantitativeValueLayer {
	return &NullableGridpointQuantitativeValueLayer{value: val, isSet: true}
}

func (v NullableGridpointQuantitativeValueLayer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGridpointQuantitativeValueLayer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


