/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// GridpointForecastJsonLdAllOf struct for GridpointForecastJsonLdAllOf
type GridpointForecastJsonLdAllOf struct {
	Context JsonLdContext `json:"@context"`
	// A geometry represented in Well-Known Text (WKT) format.
	Geometry NullableString `json:"geometry"`
}

// NewGridpointForecastJsonLdAllOf instantiates a new GridpointForecastJsonLdAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGridpointForecastJsonLdAllOf(context JsonLdContext, geometry NullableString) *GridpointForecastJsonLdAllOf {
	this := GridpointForecastJsonLdAllOf{}
	this.Context = context
	this.Geometry = geometry
	return &this
}

// NewGridpointForecastJsonLdAllOfWithDefaults instantiates a new GridpointForecastJsonLdAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGridpointForecastJsonLdAllOfWithDefaults() *GridpointForecastJsonLdAllOf {
	this := GridpointForecastJsonLdAllOf{}
	return &this
}

// GetContext returns the Context field value
func (o *GridpointForecastJsonLdAllOf) GetContext() JsonLdContext {
	if o == nil {
		var ret JsonLdContext
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *GridpointForecastJsonLdAllOf) GetContextOk() (*JsonLdContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *GridpointForecastJsonLdAllOf) SetContext(v JsonLdContext) {
	o.Context = v
}

// GetGeometry returns the Geometry field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GridpointForecastJsonLdAllOf) GetGeometry() string {
	if o == nil || o.Geometry.Get() == nil {
		var ret string
		return ret
	}

	return *o.Geometry.Get()
}

// GetGeometryOk returns a tuple with the Geometry field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GridpointForecastJsonLdAllOf) GetGeometryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Geometry.Get(), o.Geometry.IsSet()
}

// SetGeometry sets field value
func (o *GridpointForecastJsonLdAllOf) SetGeometry(v string) {
	o.Geometry.Set(&v)
}

func (o GridpointForecastJsonLdAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["@context"] = o.Context
	}
	if true {
		toSerialize["geometry"] = o.Geometry.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableGridpointForecastJsonLdAllOf struct {
	value *GridpointForecastJsonLdAllOf
	isSet bool
}

func (v NullableGridpointForecastJsonLdAllOf) Get() *GridpointForecastJsonLdAllOf {
	return v.value
}

func (v *NullableGridpointForecastJsonLdAllOf) Set(val *GridpointForecastJsonLdAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGridpointForecastJsonLdAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGridpointForecastJsonLdAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGridpointForecastJsonLdAllOf(val *GridpointForecastJsonLdAllOf) *NullableGridpointForecastJsonLdAllOf {
	return &NullableGridpointForecastJsonLdAllOf{value: val, isSet: true}
}

func (v NullableGridpointForecastJsonLdAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGridpointForecastJsonLdAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


