/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// GeoJsonFeatureCollection A GeoJSON feature collection. Please refer to IETF RFC 7946 for information on the GeoJSON format.
type GeoJsonFeatureCollection struct {
	Context *JsonLdContext `json:"@context,omitempty"`
	Type string `json:"type"`
	Features []GeoJsonFeature `json:"features"`
}

// NewGeoJsonFeatureCollection instantiates a new GeoJsonFeatureCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoJsonFeatureCollection(type_ string, features []GeoJsonFeature) *GeoJsonFeatureCollection {
	this := GeoJsonFeatureCollection{}
	this.Type = type_
	this.Features = features
	return &this
}

// NewGeoJsonFeatureCollectionWithDefaults instantiates a new GeoJsonFeatureCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoJsonFeatureCollectionWithDefaults() *GeoJsonFeatureCollection {
	this := GeoJsonFeatureCollection{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *GeoJsonFeatureCollection) GetContext() JsonLdContext {
	if o == nil || o.Context == nil {
		var ret JsonLdContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoJsonFeatureCollection) GetContextOk() (*JsonLdContext, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *GeoJsonFeatureCollection) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given JsonLdContext and assigns it to the Context field.
func (o *GeoJsonFeatureCollection) SetContext(v JsonLdContext) {
	o.Context = &v
}

// GetType returns the Type field value
func (o *GeoJsonFeatureCollection) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GeoJsonFeatureCollection) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GeoJsonFeatureCollection) SetType(v string) {
	o.Type = v
}

// GetFeatures returns the Features field value
func (o *GeoJsonFeatureCollection) GetFeatures() []GeoJsonFeature {
	if o == nil {
		var ret []GeoJsonFeature
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *GeoJsonFeatureCollection) GetFeaturesOk() ([]GeoJsonFeature, bool) {
	if o == nil {
		return nil, false
	}
	return o.Features, true
}

// SetFeatures sets field value
func (o *GeoJsonFeatureCollection) SetFeatures(v []GeoJsonFeature) {
	o.Features = v
}

func (o GeoJsonFeatureCollection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Context != nil {
		toSerialize["@context"] = o.Context
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["features"] = o.Features
	}
	return json.Marshal(toSerialize)
}

type NullableGeoJsonFeatureCollection struct {
	value *GeoJsonFeatureCollection
	isSet bool
}

func (v NullableGeoJsonFeatureCollection) Get() *GeoJsonFeatureCollection {
	return v.value
}

func (v *NullableGeoJsonFeatureCollection) Set(val *GeoJsonFeatureCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoJsonFeatureCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoJsonFeatureCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoJsonFeatureCollection(val *GeoJsonFeatureCollection) *NullableGeoJsonFeatureCollection {
	return &NullableGeoJsonFeatureCollection{value: val, isSet: true}
}

func (v NullableGeoJsonFeatureCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoJsonFeatureCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


