/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// TextProductTypeCollectionGraphInner struct for TextProductTypeCollectionGraphInner
type TextProductTypeCollectionGraphInner struct {
	ProductCode string `json:"productCode"`
	ProductName string `json:"productName"`
}

// NewTextProductTypeCollectionGraphInner instantiates a new TextProductTypeCollectionGraphInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTextProductTypeCollectionGraphInner(productCode string, productName string) *TextProductTypeCollectionGraphInner {
	this := TextProductTypeCollectionGraphInner{}
	this.ProductCode = productCode
	this.ProductName = productName
	return &this
}

// NewTextProductTypeCollectionGraphInnerWithDefaults instantiates a new TextProductTypeCollectionGraphInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTextProductTypeCollectionGraphInnerWithDefaults() *TextProductTypeCollectionGraphInner {
	this := TextProductTypeCollectionGraphInner{}
	return &this
}

// GetProductCode returns the ProductCode field value
func (o *TextProductTypeCollectionGraphInner) GetProductCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductCode
}

// GetProductCodeOk returns a tuple with the ProductCode field value
// and a boolean to check if the value has been set.
func (o *TextProductTypeCollectionGraphInner) GetProductCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductCode, true
}

// SetProductCode sets field value
func (o *TextProductTypeCollectionGraphInner) SetProductCode(v string) {
	o.ProductCode = v
}

// GetProductName returns the ProductName field value
func (o *TextProductTypeCollectionGraphInner) GetProductName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductName
}

// GetProductNameOk returns a tuple with the ProductName field value
// and a boolean to check if the value has been set.
func (o *TextProductTypeCollectionGraphInner) GetProductNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductName, true
}

// SetProductName sets field value
func (o *TextProductTypeCollectionGraphInner) SetProductName(v string) {
	o.ProductName = v
}

func (o TextProductTypeCollectionGraphInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["productCode"] = o.ProductCode
	}
	if true {
		toSerialize["productName"] = o.ProductName
	}
	return json.Marshal(toSerialize)
}

type NullableTextProductTypeCollectionGraphInner struct {
	value *TextProductTypeCollectionGraphInner
	isSet bool
}

func (v NullableTextProductTypeCollectionGraphInner) Get() *TextProductTypeCollectionGraphInner {
	return v.value
}

func (v *NullableTextProductTypeCollectionGraphInner) Set(val *TextProductTypeCollectionGraphInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTextProductTypeCollectionGraphInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTextProductTypeCollectionGraphInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTextProductTypeCollectionGraphInner(val *TextProductTypeCollectionGraphInner) *NullableTextProductTypeCollectionGraphInner {
	return &NullableTextProductTypeCollectionGraphInner{value: val, isSet: true}
}

func (v NullableTextProductTypeCollectionGraphInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTextProductTypeCollectionGraphInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


