/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// RelativeLocationGeoJsonAllOf struct for RelativeLocationGeoJsonAllOf
type RelativeLocationGeoJsonAllOf struct {
	Properties *RelativeLocation `json:"properties,omitempty"`
}

// NewRelativeLocationGeoJsonAllOf instantiates a new RelativeLocationGeoJsonAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelativeLocationGeoJsonAllOf() *RelativeLocationGeoJsonAllOf {
	this := RelativeLocationGeoJsonAllOf{}
	return &this
}

// NewRelativeLocationGeoJsonAllOfWithDefaults instantiates a new RelativeLocationGeoJsonAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelativeLocationGeoJsonAllOfWithDefaults() *RelativeLocationGeoJsonAllOf {
	this := RelativeLocationGeoJsonAllOf{}
	return &this
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *RelativeLocationGeoJsonAllOf) GetProperties() RelativeLocation {
	if o == nil || o.Properties == nil {
		var ret RelativeLocation
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelativeLocationGeoJsonAllOf) GetPropertiesOk() (*RelativeLocation, bool) {
	if o == nil || o.Properties == nil {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *RelativeLocationGeoJsonAllOf) HasProperties() bool {
	if o != nil && o.Properties != nil {
		return true
	}

	return false
}

// SetProperties gets a reference to the given RelativeLocation and assigns it to the Properties field.
func (o *RelativeLocationGeoJsonAllOf) SetProperties(v RelativeLocation) {
	o.Properties = &v
}

func (o RelativeLocationGeoJsonAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	return json.Marshal(toSerialize)
}

type NullableRelativeLocationGeoJsonAllOf struct {
	value *RelativeLocationGeoJsonAllOf
	isSet bool
}

func (v NullableRelativeLocationGeoJsonAllOf) Get() *RelativeLocationGeoJsonAllOf {
	return v.value
}

func (v *NullableRelativeLocationGeoJsonAllOf) Set(val *RelativeLocationGeoJsonAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableRelativeLocationGeoJsonAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableRelativeLocationGeoJsonAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelativeLocationGeoJsonAllOf(val *RelativeLocationGeoJsonAllOf) *NullableRelativeLocationGeoJsonAllOf {
	return &NullableRelativeLocationGeoJsonAllOf{value: val, isSet: true}
}

func (v NullableRelativeLocationGeoJsonAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelativeLocationGeoJsonAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


