/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// ObservationStationCollectionGeoJson struct for ObservationStationCollectionGeoJson
type ObservationStationCollectionGeoJson struct {
	Context *JsonLdContext `json:"@context,omitempty"`
	Type string `json:"type"`
	Features []ObservationStationGeoJsonAllOf `json:"features"`
	ObservationStations []string `json:"observationStations,omitempty"`
}

// NewObservationStationCollectionGeoJson instantiates a new ObservationStationCollectionGeoJson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObservationStationCollectionGeoJson(type_ string, features []ObservationStationGeoJsonAllOf) *ObservationStationCollectionGeoJson {
	this := ObservationStationCollectionGeoJson{}
	this.Type = type_
	this.Features = features
	return &this
}

// NewObservationStationCollectionGeoJsonWithDefaults instantiates a new ObservationStationCollectionGeoJson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObservationStationCollectionGeoJsonWithDefaults() *ObservationStationCollectionGeoJson {
	this := ObservationStationCollectionGeoJson{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *ObservationStationCollectionGeoJson) GetContext() JsonLdContext {
	if o == nil || o.Context == nil {
		var ret JsonLdContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservationStationCollectionGeoJson) GetContextOk() (*JsonLdContext, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *ObservationStationCollectionGeoJson) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given JsonLdContext and assigns it to the Context field.
func (o *ObservationStationCollectionGeoJson) SetContext(v JsonLdContext) {
	o.Context = &v
}

// GetType returns the Type field value
func (o *ObservationStationCollectionGeoJson) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ObservationStationCollectionGeoJson) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ObservationStationCollectionGeoJson) SetType(v string) {
	o.Type = v
}

// GetFeatures returns the Features field value
func (o *ObservationStationCollectionGeoJson) GetFeatures() []ObservationStationGeoJsonAllOf {
	if o == nil {
		var ret []ObservationStationGeoJsonAllOf
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *ObservationStationCollectionGeoJson) GetFeaturesOk() ([]ObservationStationGeoJsonAllOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.Features, true
}

// SetFeatures sets field value
func (o *ObservationStationCollectionGeoJson) SetFeatures(v []ObservationStationGeoJsonAllOf) {
	o.Features = v
}

// GetObservationStations returns the ObservationStations field value if set, zero value otherwise.
func (o *ObservationStationCollectionGeoJson) GetObservationStations() []string {
	if o == nil || o.ObservationStations == nil {
		var ret []string
		return ret
	}
	return o.ObservationStations
}

// GetObservationStationsOk returns a tuple with the ObservationStations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservationStationCollectionGeoJson) GetObservationStationsOk() ([]string, bool) {
	if o == nil || o.ObservationStations == nil {
		return nil, false
	}
	return o.ObservationStations, true
}

// HasObservationStations returns a boolean if a field has been set.
func (o *ObservationStationCollectionGeoJson) HasObservationStations() bool {
	if o != nil && o.ObservationStations != nil {
		return true
	}

	return false
}

// SetObservationStations gets a reference to the given []string and assigns it to the ObservationStations field.
func (o *ObservationStationCollectionGeoJson) SetObservationStations(v []string) {
	o.ObservationStations = v
}

func (o ObservationStationCollectionGeoJson) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Context != nil {
		toSerialize["@context"] = o.Context
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["features"] = o.Features
	}
	if o.ObservationStations != nil {
		toSerialize["observationStations"] = o.ObservationStations
	}
	return json.Marshal(toSerialize)
}

type NullableObservationStationCollectionGeoJson struct {
	value *ObservationStationCollectionGeoJson
	isSet bool
}

func (v NullableObservationStationCollectionGeoJson) Get() *ObservationStationCollectionGeoJson {
	return v.value
}

func (v *NullableObservationStationCollectionGeoJson) Set(val *ObservationStationCollectionGeoJson) {
	v.value = val
	v.isSet = true
}

func (v NullableObservationStationCollectionGeoJson) IsSet() bool {
	return v.isSet
}

func (v *NullableObservationStationCollectionGeoJson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObservationStationCollectionGeoJson(val *ObservationStationCollectionGeoJson) *NullableObservationStationCollectionGeoJson {
	return &NullableObservationStationCollectionGeoJson{value: val, isSet: true}
}

func (v NullableObservationStationCollectionGeoJson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObservationStationCollectionGeoJson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


