/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// AlertCollectionGeoJsonAllOf struct for AlertCollectionGeoJsonAllOf
type AlertCollectionGeoJsonAllOf struct {
	Features []AlertCollectionGeoJsonAllOfFeatures `json:"features,omitempty"`
}

// NewAlertCollectionGeoJsonAllOf instantiates a new AlertCollectionGeoJsonAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertCollectionGeoJsonAllOf() *AlertCollectionGeoJsonAllOf {
	this := AlertCollectionGeoJsonAllOf{}
	return &this
}

// NewAlertCollectionGeoJsonAllOfWithDefaults instantiates a new AlertCollectionGeoJsonAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertCollectionGeoJsonAllOfWithDefaults() *AlertCollectionGeoJsonAllOf {
	this := AlertCollectionGeoJsonAllOf{}
	return &this
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *AlertCollectionGeoJsonAllOf) GetFeatures() []AlertCollectionGeoJsonAllOfFeatures {
	if o == nil || o.Features == nil {
		var ret []AlertCollectionGeoJsonAllOfFeatures
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertCollectionGeoJsonAllOf) GetFeaturesOk() ([]AlertCollectionGeoJsonAllOfFeatures, bool) {
	if o == nil || o.Features == nil {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *AlertCollectionGeoJsonAllOf) HasFeatures() bool {
	if o != nil && o.Features != nil {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []AlertCollectionGeoJsonAllOfFeatures and assigns it to the Features field.
func (o *AlertCollectionGeoJsonAllOf) SetFeatures(v []AlertCollectionGeoJsonAllOfFeatures) {
	o.Features = v
}

func (o AlertCollectionGeoJsonAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Features != nil {
		toSerialize["features"] = o.Features
	}
	return json.Marshal(toSerialize)
}

type NullableAlertCollectionGeoJsonAllOf struct {
	value *AlertCollectionGeoJsonAllOf
	isSet bool
}

func (v NullableAlertCollectionGeoJsonAllOf) Get() *AlertCollectionGeoJsonAllOf {
	return v.value
}

func (v *NullableAlertCollectionGeoJsonAllOf) Set(val *AlertCollectionGeoJsonAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertCollectionGeoJsonAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertCollectionGeoJsonAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertCollectionGeoJsonAllOf(val *AlertCollectionGeoJsonAllOf) *NullableAlertCollectionGeoJsonAllOf {
	return &NullableAlertCollectionGeoJsonAllOf{value: val, isSet: true}
}

func (v NullableAlertCollectionGeoJsonAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertCollectionGeoJsonAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


