/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// IconsSummary200ResponseIconsValue struct for IconsSummary200ResponseIconsValue
type IconsSummary200ResponseIconsValue struct {
	Description string `json:"description"`
}

// NewIconsSummary200ResponseIconsValue instantiates a new IconsSummary200ResponseIconsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIconsSummary200ResponseIconsValue(description string) *IconsSummary200ResponseIconsValue {
	this := IconsSummary200ResponseIconsValue{}
	this.Description = description
	return &this
}

// NewIconsSummary200ResponseIconsValueWithDefaults instantiates a new IconsSummary200ResponseIconsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIconsSummary200ResponseIconsValueWithDefaults() *IconsSummary200ResponseIconsValue {
	this := IconsSummary200ResponseIconsValue{}
	return &this
}

// GetDescription returns the Description field value
func (o *IconsSummary200ResponseIconsValue) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *IconsSummary200ResponseIconsValue) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *IconsSummary200ResponseIconsValue) SetDescription(v string) {
	o.Description = v
}

func (o IconsSummary200ResponseIconsValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableIconsSummary200ResponseIconsValue struct {
	value *IconsSummary200ResponseIconsValue
	isSet bool
}

func (v NullableIconsSummary200ResponseIconsValue) Get() *IconsSummary200ResponseIconsValue {
	return v.value
}

func (v *NullableIconsSummary200ResponseIconsValue) Set(val *IconsSummary200ResponseIconsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableIconsSummary200ResponseIconsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableIconsSummary200ResponseIconsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIconsSummary200ResponseIconsValue(val *IconsSummary200ResponseIconsValue) *NullableIconsSummary200ResponseIconsValue {
	return &NullableIconsSummary200ResponseIconsValue{value: val, isSet: true}
}

func (v NullableIconsSummary200ResponseIconsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIconsSummary200ResponseIconsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


