/*
weather.gov API

weather.gov API

API version: 1.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weatherApi

import (
	"encoding/json"
)

// ZoneGeoJsonAllOf struct for ZoneGeoJsonAllOf
type ZoneGeoJsonAllOf struct {
	Properties *Zone `json:"properties,omitempty"`
}

// NewZoneGeoJsonAllOf instantiates a new ZoneGeoJsonAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZoneGeoJsonAllOf() *ZoneGeoJsonAllOf {
	this := ZoneGeoJsonAllOf{}
	return &this
}

// NewZoneGeoJsonAllOfWithDefaults instantiates a new ZoneGeoJsonAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZoneGeoJsonAllOfWithDefaults() *ZoneGeoJsonAllOf {
	this := ZoneGeoJsonAllOf{}
	return &this
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *ZoneGeoJsonAllOf) GetProperties() Zone {
	if o == nil || o.Properties == nil {
		var ret Zone
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZoneGeoJsonAllOf) GetPropertiesOk() (*Zone, bool) {
	if o == nil || o.Properties == nil {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ZoneGeoJsonAllOf) HasProperties() bool {
	if o != nil && o.Properties != nil {
		return true
	}

	return false
}

// SetProperties gets a reference to the given Zone and assigns it to the Properties field.
func (o *ZoneGeoJsonAllOf) SetProperties(v Zone) {
	o.Properties = &v
}

func (o ZoneGeoJsonAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	return json.Marshal(toSerialize)
}

type NullableZoneGeoJsonAllOf struct {
	value *ZoneGeoJsonAllOf
	isSet bool
}

func (v NullableZoneGeoJsonAllOf) Get() *ZoneGeoJsonAllOf {
	return v.value
}

func (v *NullableZoneGeoJsonAllOf) Set(val *ZoneGeoJsonAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableZoneGeoJsonAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableZoneGeoJsonAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZoneGeoJsonAllOf(val *ZoneGeoJsonAllOf) *NullableZoneGeoJsonAllOf {
	return &NullableZoneGeoJsonAllOf{value: val, isSet: true}
}

func (v NullableZoneGeoJsonAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZoneGeoJsonAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


